export { default as Navbar } from "./Navbar"
export { default as Footer } from "./Footer"

export { default as Hero } from "./Hero"
export { default as BronHotel } from "./BronHotel"
export { default as BronPaket } from "./BronPaket"
export { default as SpecialPackages } from "./SpecialPackages"
export { default as SimplePackages } from "./SimplePackages"
export { default as Gallery } from "./Gallery"
export { default as Contact } from "./Contact"